### PR TITLE
Milestone #3: Contact Form Validation

### PR DESCRIPTION
**Pull request by Anjacodes**
In this milestone, we:

* Added form validation to the email input
* Ensured that default is prevented if the email address is not in lowercase
* Allowed form to submit if the email address is in all lowercase

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Anjacodes @TheLuisAbarca  👋🏽 

Good job working on the project so far! 
✔️  You followed the Figma template
✔️  All your linters pass
✔️  The form is submitted successfully
✔️  Your design is neat
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- The error that displays when a user submits an email with any capitalized letter should be displayed close to the get in touch button as stated in the project requirement
Screenshot 2021-11-11 at 19 06 45
However, in your project, the error message is displayed just above the input field
Screenshot 2021-11-11 at 19 07 06
Please fix it

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by TheLuisAbarca** [comment]
Thank you for your feedback @Ghiftee! We have move the error message as you kindly ask us to do. Is it done on commit 
619f83b

**Review by ArthurGC — APPROVED** [review]
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  team

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Anjacodes** [comment]
Hi Arthur,

Thank you for approving!
On my dashboard the status still shows as “Review Pending”.
Do you have any idea what could be the cause of that?

Grateful for any ideas!
Thank you,
Anja

**Comment by ArthurGC** [comment]
Don't worry. Now you should have the submit button. 😉

**Pull request merged**
